- name: MySQL configuration
  hosts: backend
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.pavandevopssept2024.online
    
  tasks:
    - name: Disable the Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable the Node.js version 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install the Node.js and MySQL packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: 
        - nodejs
        - mysql

    - name: Create the expense user
      ansible.builtin.user:
        name: expense

    - name: Create the app directory 
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the application file and store it in the temp directory
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: Unzip the application code to the app directory
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: Install the Node.js dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Copy the backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: 
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: Import the MySQL schema
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
        target: /app/schema/backend.sql
        name: all
        state: import

    - name: Restart service backend, in all cases
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: crond

