- name: Frontend server configuration
  hosts: frontend
  become: yes
  
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove all files in the html folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create the html folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download the application file and store it in the temp directory
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Unzip the application code to the html directory
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy the frontend service configuration file
      ansible.builtin.copy:
        src: frontend.service
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart Nginx service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: nginx