- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.pavandevopssept2024.online

  tasks:
    - name: install boto3 and botocore
      ansible.builtin.pip:
        name: 
          - boto3
          - botocore
        executable: pip3.9

    - name: installing the mysql server 
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: starting the mysql server 
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: connecting to sql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
      ignore_errors: true
      register: mysql_info

    - name: print the sql info
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"

    - name: setup the mysql root user password
      ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"
      when: mysql_info.failed is true
