- name: create the ec2 instance and route 53 records
  hosts: local
  connection: local
  vars:
    SUBNETID: subnet-05bb7d68987410a49
    security_group_id: sg-01f3d8a39dd178aff
    ami_id: ami-09c813fb71547fc4f
    instances:
      - mysql
      - backend
      - frontend
    zone: pavandevopssept2024.online

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ SUBNETID }}"
        instance_type: "t3.micro"
        security_group: "{{ security_group_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: print the results
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    - name: add the route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait_timeout: 300
        overwrite: true
      loop: "{{ ec2_instances.results }}"
